name: SSH Actions Demo

run-name: ${{ github.actor }} is testing out SSH on GitHub Actions 🚀

on: [push]

jobs:
  SSH-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSH key
        run: |
          env
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p 22 ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts
          ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} touch from_workflow
          #          sudo apt-get install sshpass
